name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/android-perf.yml'
      - 'lib/android/**'
      - 'lib/common/**'
      - 'resources/audio_samples/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+']
    paths:
      - '.github/workflows/android-perf.yml'
      - 'lib/android/**'
      - 'lib/common/**'
      - 'resources/audio_samples/**'

defaults:
  run:
    working-directory: binding/android/KoalaTestApp

jobs:
  build:
    name: Run Android Speed Tests on AppCenter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [single-android, 32bit-android]
        include:
        - device: single-android
          performanceThresholdSec: 0.4
        - device: 32bit-android
          performanceThresholdSec: 3.0

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Inject Number of Iterations
      run: echo numTestIterations="30" >> local.properties

    - name: Inject Proc Performance Threshold
      run: echo performanceThresholdSec="${{ matrix.performanceThresholdSec }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest -DtestBuildType=perf

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Koala-Android"
        --devices "Picovoice/${{ matrix.device }}"
        --app-path koala-test-app/build/outputs/apk/debug/koala-test-app-debug.apk
        --test-series "koala-android"
        --locale "en_US"
        --build-dir koala-test-app/build/outputs/apk/androidTest/debug

